#madlibe.yml
on: issues
name: Create MadLibs in GitHub Issues
jobs:
  madblib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@v.0.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}